In [1]:
import torch

In [2]:
torch.__version__

'1.10.1+cu113'

In [3]:
x = torch.empty(4, 2)
print(x)

tensor([[1.6689e-07, 1.6968e-07],
        [4.1301e-08, 1.0800e-05],
        [8.1811e+20, 1.3664e+22],
        [1.6986e-07, 1.3399e-08]])


In [5]:
x = torch.rand(4, 2)
print(x)

tensor([[0.4440, 0.2389],
        [0.2187, 0.2192],
        [0.6288, 0.6864],
        [0.8650, 0.9001]])


In [6]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [7]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [8]:
x = x.new_ones(2, 4, dtype=torch.float)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [9]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.0326,  1.3376, -0.6942, -0.6683],
        [ 1.5748,  1.1568, -1.5362, -0.5720]])


In [10]:
print(x.size())

torch.Size([2, 4])


In [11]:
y = torch.rand(2, 4, dtype=float)

print(y)
print(x+y)
    

tensor([[0.6257, 0.6427, 0.0110, 0.6396],
        [0.7879, 0.9216, 0.2753, 0.8706]], dtype=torch.float64)
tensor([[ 0.6583,  1.9804, -0.6832, -0.0287],
        [ 2.3627,  2.0784, -1.2609,  0.2986]], dtype=torch.float64)


In [12]:
print(torch.add(x, y))


tensor([[ 0.6583,  1.9804, -0.6832, -0.0287],
        [ 2.3627,  2.0784, -1.2609,  0.2986]], dtype=torch.float64)
